#include "mmthemes.h"

// NOTE: global function descriptions in header.

// static values ------------------------------------------------------------------------------------------------------------

const char* const p_mainThemeSamplesA[50] = { MM_COMMON_MUSICPATH_MAIN_RAWA0, MM_COMMON_MUSICPATH_MAIN_RAWA1, MM_COMMON_MUSICPATH_MAIN_RAWA2, MM_COMMON_MUSICPATH_MAIN_RAWA3, MM_COMMON_MUSICPATH_MAIN_RAWA4, MM_COMMON_MUSICPATH_MAIN_RAWA5, MM_COMMON_MUSICPATH_MAIN_RAWA6, MM_COMMON_MUSICPATH_MAIN_RAWA7, MM_COMMON_MUSICPATH_MAIN_RAWA8, MM_COMMON_MUSICPATH_MAIN_RAWA9, MM_COMMON_MUSICPATH_MAIN_RAWA10, MM_COMMON_MUSICPATH_MAIN_RAWA11, MM_COMMON_MUSICPATH_MAIN_RAWA12, MM_COMMON_MUSICPATH_MAIN_RAWA13, MM_COMMON_MUSICPATH_MAIN_RAWA14, MM_COMMON_MUSICPATH_MAIN_RAWA15, MM_COMMON_MUSICPATH_MAIN_RAWA16, MM_COMMON_MUSICPATH_MAIN_RAWA17, MM_COMMON_MUSICPATH_MAIN_RAWA18, MM_COMMON_MUSICPATH_MAIN_RAWA19, MM_COMMON_MUSICPATH_MAIN_RAWA20, MM_COMMON_MUSICPATH_MAIN_RAWA21, MM_COMMON_MUSICPATH_MAIN_RAWA22, MM_COMMON_MUSICPATH_MAIN_RAWA23, MM_COMMON_MUSICPATH_MAIN_RAWA24, MM_COMMON_MUSICPATH_MAIN_RAWA25, MM_COMMON_MUSICPATH_MAIN_RAWA26, MM_COMMON_MUSICPATH_MAIN_RAWA27, MM_COMMON_MUSICPATH_MAIN_RAWA28, MM_COMMON_MUSICPATH_MAIN_RAWA29, MM_COMMON_MUSICPATH_MAIN_RAWA30, MM_COMMON_MUSICPATH_MAIN_RAWA31, MM_COMMON_MUSICPATH_MAIN_RAWA32, MM_COMMON_MUSICPATH_MAIN_RAWA33, MM_COMMON_MUSICPATH_MAIN_RAWA34, MM_COMMON_MUSICPATH_MAIN_RAWA35, MM_COMMON_MUSICPATH_MAIN_RAWA36, MM_COMMON_MUSICPATH_MAIN_RAWA37, MM_COMMON_MUSICPATH_MAIN_RAWA38, MM_COMMON_MUSICPATH_MAIN_RAWA39, MM_COMMON_MUSICPATH_MAIN_RAWA40, MM_COMMON_MUSICPATH_MAIN_RAWA41, MM_COMMON_MUSICPATH_MAIN_RAWA42, MM_COMMON_MUSICPATH_MAIN_RAWA43, MM_COMMON_MUSICPATH_MAIN_RAWA44, MM_COMMON_MUSICPATH_MAIN_RAWA45, MM_COMMON_MUSICPATH_MAIN_RAWA46, MM_COMMON_MUSICPATH_MAIN_RAWA47, MM_COMMON_MUSICPATH_MAIN_RAWA48, MM_COMMON_MUSICPATH_MAIN_RAWA49 };

const char* const p_mainThemeSamplesB[50] = { MM_COMMON_MUSICPATH_MAIN_RAWB0, MM_COMMON_MUSICPATH_MAIN_RAWB1, MM_COMMON_MUSICPATH_MAIN_RAWB2, MM_COMMON_MUSICPATH_MAIN_RAWB3, MM_COMMON_MUSICPATH_MAIN_RAWB4, MM_COMMON_MUSICPATH_MAIN_RAWB5, MM_COMMON_MUSICPATH_MAIN_RAWB6, MM_COMMON_MUSICPATH_MAIN_RAWB7, MM_COMMON_MUSICPATH_MAIN_RAWB8, MM_COMMON_MUSICPATH_MAIN_RAWB9, MM_COMMON_MUSICPATH_MAIN_RAWB10, MM_COMMON_MUSICPATH_MAIN_RAWB11, MM_COMMON_MUSICPATH_MAIN_RAWB12, MM_COMMON_MUSICPATH_MAIN_RAWB13, MM_COMMON_MUSICPATH_MAIN_RAWB14, MM_COMMON_MUSICPATH_MAIN_RAWB15, MM_COMMON_MUSICPATH_MAIN_RAWB16, MM_COMMON_MUSICPATH_MAIN_RAWB17, MM_COMMON_MUSICPATH_MAIN_RAWB18, MM_COMMON_MUSICPATH_MAIN_RAWB19, MM_COMMON_MUSICPATH_MAIN_RAWB20, MM_COMMON_MUSICPATH_MAIN_RAWB21, MM_COMMON_MUSICPATH_MAIN_RAWB22, MM_COMMON_MUSICPATH_MAIN_RAWB23, MM_COMMON_MUSICPATH_MAIN_RAWB24, MM_COMMON_MUSICPATH_MAIN_RAWB25, MM_COMMON_MUSICPATH_MAIN_RAWB26, MM_COMMON_MUSICPATH_MAIN_RAWB27, MM_COMMON_MUSICPATH_MAIN_RAWB28, MM_COMMON_MUSICPATH_MAIN_RAWB29, MM_COMMON_MUSICPATH_MAIN_RAWB30, MM_COMMON_MUSICPATH_MAIN_RAWB31, MM_COMMON_MUSICPATH_MAIN_RAWB32, MM_COMMON_MUSICPATH_MAIN_RAWB33, MM_COMMON_MUSICPATH_MAIN_RAWB34, MM_COMMON_MUSICPATH_MAIN_RAWB35, MM_COMMON_MUSICPATH_MAIN_RAWB36, MM_COMMON_MUSICPATH_MAIN_RAWB37, MM_COMMON_MUSICPATH_MAIN_RAWB38, MM_COMMON_MUSICPATH_MAIN_RAWB39, MM_COMMON_MUSICPATH_MAIN_RAWB40, MM_COMMON_MUSICPATH_MAIN_RAWB41, MM_COMMON_MUSICPATH_MAIN_RAWB42, MM_COMMON_MUSICPATH_MAIN_RAWB43, MM_COMMON_MUSICPATH_MAIN_RAWB44, MM_COMMON_MUSICPATH_MAIN_RAWB45, MM_COMMON_MUSICPATH_MAIN_RAWB46, MM_COMMON_MUSICPATH_MAIN_RAWB47, MM_COMMON_MUSICPATH_MAIN_RAWB48, MM_COMMON_MUSICPATH_MAIN_RAWB49 };

const char* const p_mainThemeSamplesC[50] = { MM_COMMON_MUSICPATH_MAIN_RAWC0, MM_COMMON_MUSICPATH_MAIN_RAWC1, MM_COMMON_MUSICPATH_MAIN_RAWC2, MM_COMMON_MUSICPATH_MAIN_RAWC3, MM_COMMON_MUSICPATH_MAIN_RAWC4, MM_COMMON_MUSICPATH_MAIN_RAWC5, MM_COMMON_MUSICPATH_MAIN_RAWC6, MM_COMMON_MUSICPATH_MAIN_RAWC7, MM_COMMON_MUSICPATH_MAIN_RAWC8, MM_COMMON_MUSICPATH_MAIN_RAWC9, MM_COMMON_MUSICPATH_MAIN_RAWC10, MM_COMMON_MUSICPATH_MAIN_RAWC11, MM_COMMON_MUSICPATH_MAIN_RAWC12, MM_COMMON_MUSICPATH_MAIN_RAWC13, MM_COMMON_MUSICPATH_MAIN_RAWC14, MM_COMMON_MUSICPATH_MAIN_RAWC15, MM_COMMON_MUSICPATH_MAIN_RAWC16, MM_COMMON_MUSICPATH_MAIN_RAWC17, MM_COMMON_MUSICPATH_MAIN_RAWC18, MM_COMMON_MUSICPATH_MAIN_RAWC19, MM_COMMON_MUSICPATH_MAIN_RAWC20, MM_COMMON_MUSICPATH_MAIN_RAWC21, MM_COMMON_MUSICPATH_MAIN_RAWC22, MM_COMMON_MUSICPATH_MAIN_RAWC23, MM_COMMON_MUSICPATH_MAIN_RAWC24, MM_COMMON_MUSICPATH_MAIN_RAWC25, MM_COMMON_MUSICPATH_MAIN_RAWC26, MM_COMMON_MUSICPATH_MAIN_RAWC27, MM_COMMON_MUSICPATH_MAIN_RAWC28, MM_COMMON_MUSICPATH_MAIN_RAWC29, MM_COMMON_MUSICPATH_MAIN_RAWC30, MM_COMMON_MUSICPATH_MAIN_RAWC31, MM_COMMON_MUSICPATH_MAIN_RAWC32, MM_COMMON_MUSICPATH_MAIN_RAWC33, MM_COMMON_MUSICPATH_MAIN_RAWC34, MM_COMMON_MUSICPATH_MAIN_RAWC35, MM_COMMON_MUSICPATH_MAIN_RAWC36, MM_COMMON_MUSICPATH_MAIN_RAWC37, MM_COMMON_MUSICPATH_MAIN_RAWC38, MM_COMMON_MUSICPATH_MAIN_RAWC39, MM_COMMON_MUSICPATH_MAIN_RAWC40, MM_COMMON_MUSICPATH_MAIN_RAWC41, MM_COMMON_MUSICPATH_MAIN_RAWC42, MM_COMMON_MUSICPATH_MAIN_RAWC43, MM_COMMON_MUSICPATH_MAIN_RAWC44, MM_COMMON_MUSICPATH_MAIN_RAWC45, MM_COMMON_MUSICPATH_MAIN_RAWC46, MM_COMMON_MUSICPATH_MAIN_RAWC47, MM_COMMON_MUSICPATH_MAIN_RAWC48, MM_COMMON_MUSICPATH_MAIN_RAWC49 };

const char* const p_mainThemeSamplesD[50] = { MM_COMMON_MUSICPATH_MAIN_RAWD0, MM_COMMON_MUSICPATH_MAIN_RAWD1, MM_COMMON_MUSICPATH_MAIN_RAWD2, MM_COMMON_MUSICPATH_MAIN_RAWD3, MM_COMMON_MUSICPATH_MAIN_RAWD4, MM_COMMON_MUSICPATH_MAIN_RAWD5, MM_COMMON_MUSICPATH_MAIN_RAWD6, MM_COMMON_MUSICPATH_MAIN_RAWD7, MM_COMMON_MUSICPATH_MAIN_RAWD8, MM_COMMON_MUSICPATH_MAIN_RAWD9, MM_COMMON_MUSICPATH_MAIN_RAWD10, MM_COMMON_MUSICPATH_MAIN_RAWD11, MM_COMMON_MUSICPATH_MAIN_RAWD12, MM_COMMON_MUSICPATH_MAIN_RAWD13, MM_COMMON_MUSICPATH_MAIN_RAWD14, MM_COMMON_MUSICPATH_MAIN_RAWD15, MM_COMMON_MUSICPATH_MAIN_RAWD16, MM_COMMON_MUSICPATH_MAIN_RAWD17, MM_COMMON_MUSICPATH_MAIN_RAWD18, MM_COMMON_MUSICPATH_MAIN_RAWD19, MM_COMMON_MUSICPATH_MAIN_RAWD20, MM_COMMON_MUSICPATH_MAIN_RAWD21, MM_COMMON_MUSICPATH_MAIN_RAWD22, MM_COMMON_MUSICPATH_MAIN_RAWD23, MM_COMMON_MUSICPATH_MAIN_RAWD24, MM_COMMON_MUSICPATH_MAIN_RAWD25, MM_COMMON_MUSICPATH_MAIN_RAWD26, MM_COMMON_MUSICPATH_MAIN_RAWD27, MM_COMMON_MUSICPATH_MAIN_RAWD28, MM_COMMON_MUSICPATH_MAIN_RAWD29, MM_COMMON_MUSICPATH_MAIN_RAWD30, MM_COMMON_MUSICPATH_MAIN_RAWD31, MM_COMMON_MUSICPATH_MAIN_RAWD32, MM_COMMON_MUSICPATH_MAIN_RAWD33, MM_COMMON_MUSICPATH_MAIN_RAWD34, MM_COMMON_MUSICPATH_MAIN_RAWD35, MM_COMMON_MUSICPATH_MAIN_RAWD36, MM_COMMON_MUSICPATH_MAIN_RAWD37, MM_COMMON_MUSICPATH_MAIN_RAWD38, MM_COMMON_MUSICPATH_MAIN_RAWD39, MM_COMMON_MUSICPATH_MAIN_RAWD40, MM_COMMON_MUSICPATH_MAIN_RAWD41, MM_COMMON_MUSICPATH_MAIN_RAWD42, MM_COMMON_MUSICPATH_MAIN_RAWD43, MM_COMMON_MUSICPATH_MAIN_RAWD44, MM_COMMON_MUSICPATH_MAIN_RAWD45, MM_COMMON_MUSICPATH_MAIN_RAWD46, MM_COMMON_MUSICPATH_MAIN_RAWD47, MM_COMMON_MUSICPATH_MAIN_RAWD48, MM_COMMON_MUSICPATH_MAIN_RAWD49 };

const char* const p_mainThemeSamplesE[50] = { MM_COMMON_MUSICPATH_MAIN_RAWE0, MM_COMMON_MUSICPATH_MAIN_RAWE1, MM_COMMON_MUSICPATH_MAIN_RAWE2, MM_COMMON_MUSICPATH_MAIN_RAWE3, MM_COMMON_MUSICPATH_MAIN_RAWE4, MM_COMMON_MUSICPATH_MAIN_RAWE5, MM_COMMON_MUSICPATH_MAIN_RAWE6, MM_COMMON_MUSICPATH_MAIN_RAWE7, MM_COMMON_MUSICPATH_MAIN_RAWE8, MM_COMMON_MUSICPATH_MAIN_RAWE9, MM_COMMON_MUSICPATH_MAIN_RAWE10, MM_COMMON_MUSICPATH_MAIN_RAWE11, MM_COMMON_MUSICPATH_MAIN_RAWE12, MM_COMMON_MUSICPATH_MAIN_RAWE13, MM_COMMON_MUSICPATH_MAIN_RAWE14, MM_COMMON_MUSICPATH_MAIN_RAWE15, MM_COMMON_MUSICPATH_MAIN_RAWE16, MM_COMMON_MUSICPATH_MAIN_RAWE17, MM_COMMON_MUSICPATH_MAIN_RAWE18, MM_COMMON_MUSICPATH_MAIN_RAWE19, MM_COMMON_MUSICPATH_MAIN_RAWE20, MM_COMMON_MUSICPATH_MAIN_RAWE21, MM_COMMON_MUSICPATH_MAIN_RAWE22, MM_COMMON_MUSICPATH_MAIN_RAWE23, MM_COMMON_MUSICPATH_MAIN_RAWE24, MM_COMMON_MUSICPATH_MAIN_RAWE25, MM_COMMON_MUSICPATH_MAIN_RAWE26, MM_COMMON_MUSICPATH_MAIN_RAWE27, MM_COMMON_MUSICPATH_MAIN_RAWE28, MM_COMMON_MUSICPATH_MAIN_RAWE29, MM_COMMON_MUSICPATH_MAIN_RAWE30, MM_COMMON_MUSICPATH_MAIN_RAWE31, MM_COMMON_MUSICPATH_MAIN_RAWE32, MM_COMMON_MUSICPATH_MAIN_RAWE33, MM_COMMON_MUSICPATH_MAIN_RAWE34, MM_COMMON_MUSICPATH_MAIN_RAWE35, MM_COMMON_MUSICPATH_MAIN_RAWE36, MM_COMMON_MUSICPATH_MAIN_RAWE37, MM_COMMON_MUSICPATH_MAIN_RAWE38, MM_COMMON_MUSICPATH_MAIN_RAWE39, MM_COMMON_MUSICPATH_MAIN_RAWE40, MM_COMMON_MUSICPATH_MAIN_RAWE41, MM_COMMON_MUSICPATH_MAIN_RAWE42, MM_COMMON_MUSICPATH_MAIN_RAWE43, MM_COMMON_MUSICPATH_MAIN_RAWE44, MM_COMMON_MUSICPATH_MAIN_RAWE45, MM_COMMON_MUSICPATH_MAIN_RAWE46, MM_COMMON_MUSICPATH_MAIN_RAWE47, MM_COMMON_MUSICPATH_MAIN_RAWE48, MM_COMMON_MUSICPATH_MAIN_RAWE49 };

const char* const p_mainThemeSamplesF[50] = { MM_COMMON_MUSICPATH_MAIN_RAWF0, MM_COMMON_MUSICPATH_MAIN_RAWF1, MM_COMMON_MUSICPATH_MAIN_RAWF2, MM_COMMON_MUSICPATH_MAIN_RAWF3, MM_COMMON_MUSICPATH_MAIN_RAWF4, MM_COMMON_MUSICPATH_MAIN_RAWF5, MM_COMMON_MUSICPATH_MAIN_RAWF6, MM_COMMON_MUSICPATH_MAIN_RAWF7, MM_COMMON_MUSICPATH_MAIN_RAWF8, MM_COMMON_MUSICPATH_MAIN_RAWF9, MM_COMMON_MUSICPATH_MAIN_RAWF10, MM_COMMON_MUSICPATH_MAIN_RAWF11, MM_COMMON_MUSICPATH_MAIN_RAWF12, MM_COMMON_MUSICPATH_MAIN_RAWF13, MM_COMMON_MUSICPATH_MAIN_RAWF14, MM_COMMON_MUSICPATH_MAIN_RAWF15, MM_COMMON_MUSICPATH_MAIN_RAWF16, MM_COMMON_MUSICPATH_MAIN_RAWF17, MM_COMMON_MUSICPATH_MAIN_RAWF18, MM_COMMON_MUSICPATH_MAIN_RAWF19, MM_COMMON_MUSICPATH_MAIN_RAWF20, MM_COMMON_MUSICPATH_MAIN_RAWF21, MM_COMMON_MUSICPATH_MAIN_RAWF22, MM_COMMON_MUSICPATH_MAIN_RAWF23, MM_COMMON_MUSICPATH_MAIN_RAWF24, MM_COMMON_MUSICPATH_MAIN_RAWF25, MM_COMMON_MUSICPATH_MAIN_RAWF26, MM_COMMON_MUSICPATH_MAIN_RAWF27, MM_COMMON_MUSICPATH_MAIN_RAWF28, MM_COMMON_MUSICPATH_MAIN_RAWF29, MM_COMMON_MUSICPATH_MAIN_RAWF30, MM_COMMON_MUSICPATH_MAIN_RAWF31, MM_COMMON_MUSICPATH_MAIN_RAWF32, MM_COMMON_MUSICPATH_MAIN_RAWF33, MM_COMMON_MUSICPATH_MAIN_RAWF34, MM_COMMON_MUSICPATH_MAIN_RAWF35, MM_COMMON_MUSICPATH_MAIN_RAWF36, MM_COMMON_MUSICPATH_MAIN_RAWF37, MM_COMMON_MUSICPATH_MAIN_RAWF38, MM_COMMON_MUSICPATH_MAIN_RAWF39, MM_COMMON_MUSICPATH_MAIN_RAWF40, MM_COMMON_MUSICPATH_MAIN_RAWF41, MM_COMMON_MUSICPATH_MAIN_RAWF42, MM_COMMON_MUSICPATH_MAIN_RAWF43, MM_COMMON_MUSICPATH_MAIN_RAWF44, MM_COMMON_MUSICPATH_MAIN_RAWF45, MM_COMMON_MUSICPATH_MAIN_RAWF46, MM_COMMON_MUSICPATH_MAIN_RAWF47, MM_COMMON_MUSICPATH_MAIN_RAWF48, MM_COMMON_MUSICPATH_MAIN_RAWF49 };

static int64_t p_mainLoop = -1;

static PLEX_FAKESTRING_50 p_mainThemeStr;

// ---------------------------- //
// PUBLIC FUNCTIONS:
// ---------------------------- //

// specialized functions ----------------------------------------------------------------------------------------------------

void MM_COMMON_reloadMainTheme(const size_t voiceIndex, const size_t sampleIndex)
{
	const char* mainThemeSample = NULL;

	int64_t voice = 0;

	if(voiceIndex >= 6) return;

	PLEX_clearSoundBufferByChannel(voiceIndex + 1);

	switch(voiceIndex)
	{
		case 0: mainThemeSample = p_mainThemeSamplesA[sampleIndex]; break;
		case 1: mainThemeSample = p_mainThemeSamplesB[sampleIndex]; break;
		case 2: mainThemeSample = p_mainThemeSamplesC[sampleIndex]; break;
		case 3: mainThemeSample = p_mainThemeSamplesD[sampleIndex]; break;
		case 4: mainThemeSample = p_mainThemeSamplesE[sampleIndex]; break;
		case 5: mainThemeSample = p_mainThemeSamplesF[sampleIndex]; break;
	};

	voice = MM_COMMON_preloadMusicFileToSpecificBuffer(mainThemeSample, sampleIndex + 1);

	MM_COMMON_musicChannelOff(voiceIndex + 1);

	if(voice != -1 && MM_COMMON_musicAssignBuffer(voice, voiceIndex + 1)) MM_COMMON_musicChannelOn(false, voiceIndex + 1);
}

void MM_COMMON_THEME_MAIN_start()
{
	p_mainThemeStr = PLEX_createString50("Main");
}

void MM_COMMON_playThemeMain()
{
	const size_t voiceIndex = PLEX_randomNumber(0, 49);

	p_mainLoop = MM_COMMON_preloadMusicFile(MM_COMMON_MUSICPATH_MAIN_LOOP);

	if(p_mainLoop != -1 && MM_COMMON_musicAssignBuffer(p_mainLoop, 0)) MM_COMMON_musicChannelOn(false, 0);

	for(size_t ze = 0; ze < 6; ++ze) MM_COMMON_reloadMainTheme(ze, voiceIndex);
}

void MM_COMMON_updateMainThemeVoice()
{
	if(!PLEX_isSoundPlaying(0))
	{
		const size_t sampleIndex = PLEX_randomNumber(0, 49);

		p_mainLoop = MM_COMMON_preloadMusicFile(MM_COMMON_MUSICPATH_MAIN_LOOP);

		if(p_mainLoop != -1 && MM_COMMON_musicAssignBuffer(p_mainLoop, 0)) MM_COMMON_musicChannelOn(false, 0);

		for(size_t ze = 0; ze < 6; ++ze) MM_COMMON_reloadMainTheme(ze, sampleIndex);
	}
}

// getters ------------------------------------------------------------------------------------------------------------------

PLEX_FAKESTRING_50 MM_COMMON_THEME_mainThemeStr()
{
	return p_mainThemeStr;
}
